version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "7592:7592"
    environment:
      - DATABASE_URL=postgres://postgres:admin@database:5432/classroom
    depends_on:
      - database

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "7593:7593"

  database:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: classroom
    ports:
      - "7594:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
